package com.puffinsoft.bibframe.conversion

const val BIBFRAME_ONTOLOGY = "http://id.loc.gov/ontologies/bibframe/"
const val BIBFRAME_LC_EXTENSION_ONTOLOGY = "http://id.loc.gov/ontologies/bflc/"
const val LOC_MADS_RDF = "http://www.loc.gov/mads/rdf/v1#"

const val TITLE = "http://id.loc.gov/ontologies/bibframe/Title"
const val VARIANT_TITLE = "http://id.loc.gov/ontologies/bibframe/VariantTitle"
const val PARALLEL_TITLE = "http://id.loc.gov/ontologies/bibframe/ParallelTitle"
const val TRANSCRIBED_TITLE = "http://id.loc.gov/ontologies/bflc/TranscribedTitle"

const val LOC_DATATYPES_ORGS = "http://id.loc.gov/datatypes/orgs/"
const val LOC_DATATYPES_EDTF = "http://id.loc.gov/datatypes/edtf"

const val WORK_TYPE_TEXT = "http://id.loc.gov/ontologies/bibframe/Text"
const val WORK_TYPE_MANUSCRIPT = "http://id.loc.gov/ontologies/bibframe/Manuscript"
const val WORK_TYPE_NOTATED_MUSIC = "http://id.loc.gov/ontologies/bibframe/NotatedMusic"
const val WORK_TYPE_CARTOGRAPHY = "http://id.loc.gov/ontologies/bibframe/Cartography"
const val WORK_TYPE_MOVING_IMAGE = "http://id.loc.gov/ontologies/bibframe/MovingImage"
const val WORK_TYPE_NON_MUSIC_AUDIO = "http://id.loc.gov/ontologies/bibframe/NonMusicAudio"
const val WORK_TYPE_MUSIC_AUDIO = "http://id.loc.gov/ontologies/bibframe/MusicAudio"
const val WORK_TYPE_STILL_IMAGE = "http://id.loc.gov/ontologies/bibframe/StillImage"
const val WORK_TYPE_MULTIMEDIA = "http://id.loc.gov/ontologies/bibframe/Multimedia"
const val WORK_TYPE_MIXED_MATERIAL = "http://id.loc.gov/ontologies/bibframe/MixedMaterial"
const val WORK_TYPE_OBJECT = "http://id.loc.gov/ontologies/bibframe/Object"
const val WORK_TYPE_COLLECTION = "http://id.loc.gov/ontologies/bibframe/Collection"
const val WORK_TYPE_INTEGRATING = "http://id.loc.gov/ontologies/bibframe/Integrating"
const val WORK_TYPE_MONOGRAPH = "http://id.loc.gov/ontologies/bibframe/Monograph"
const val WORK_TYPE_SERIAL = "http://id.loc.gov/ontologies/bibframe/Serial"

const val RELATORS_URI = "http://id.loc.gov/vocabulary/relators"
const val NOTE_TYPE_URI = "http://id.loc.gov/vocabulary/mnotetype"
const val CAPTURE_STORAGE_URI = "http://id.loc.gov/vocabulary/mcapturestorage"
const val PLAYBACK_URI = "http://id.loc.gov/vocabulary/mplayback"
const val TAPE_CONFIG_URI = "http://id.loc.gov/vocabulary/mtapeconfig"
const val GROOVE_URI = "http://id.loc.gov/vocabulary/mgroove"
const val PLAY_SPEED_URI = "http://id.loc.gov/vocabulary/mplayspeed"
const val RECORDING_MEDIUM_URI = "http://id.loc.gov/vocabulary/mrecmedium"
const val SPECIAL_PLAYBACK_URI = "http://id.loc.gov/vocabulary/mspecplayback"
const val RECORDING_TYPE_URI = "http://id.loc.gov/vocabulary/mrectype"
const val COLOR_CONTENT_URI = "http://id.loc.gov/vocabulary/mcolor"
const val ILLUSTRATIVE_CONTENT_URI = "http://id.loc.gov/vocabulary/millus"
const val BOOK_FORMAT_URI = "http://id.loc.gov/vocabulary/bookformat"
const val FONT_SIZE_URI = "http://id.loc.gov/vocabulary/mfont"
const val GENERATION_URI = "http://id.loc.gov/vocabulary/mgeneration"
const val LAYOUT_URI = "http://id.loc.gov/vocabulary/mlayout"
const val SUPPORT_MATERIAL_URI = "http://id.loc.gov/vocabulary/mmaterial"
const val POLARITY_URI = "http://id.loc.gov/vocabulary/mpolarity"
const val PRESENTATION_FORMAT_URI = "http://id.loc.gov/vocabulary/mpresformat"
const val PRODUCTION_METHOD_URI = "http://id.loc.gov/vocabulary/mproduction"
const val REDUCTION_RATIO_URI = "http://id.loc.gov/vocabulary/mreductionratio"
const val FILE_TYPE_URI = "http://id.loc.gov/vocabulary/mfiletype"
const val ENCODING_FORMAT_URI = "http://id.loc.gov/vocabulary/mencformat"
const val REGION_ENCODING_URI = "http://id.loc.gov/vocabulary/mregencoding"
const val BROADCAST_STANDARD_URI = "http://id.loc.gov/vocabulary/mbroadstd"
const val VIDEO_FORMAT_URI = "http://id.loc.gov/vocabulary/mvidformat"
const val MUSIC_NOTATION_URI = "http://id.loc.gov/vocabulary/mmusnotation"
const val MUSIC_FORMAT_URI = "http://id.loc.gov/vocabulary/mmusicformat"
const val INTENDED_AUDIENCE_URI = "http://id.loc.gov/vocabulary/maudience"